baseURL = 'https://birchpoplar.github.io/'
languageCode = 'en-us'
title = 'My Tech Blog'
theme = "ritzy"

[params]
  author = "Johnnie Walker"
  description = "Rather unstructured tech writings"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
